version: '3'

services:

  smartphones:
    build:
      context: ./services/smartphones
      dockerfile: Dockerfile-dev
    volumes:
      - './services/smartphones:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@smartphones-db:5432/smartphones_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@smartphones-db:5432/smartphones_test
    depends_on:
      - smartphones-db

  smartphones-db:
    build:
      context: ./services/smartphones/project/db
      dockerfile: Dockerfile
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - smartphones